services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: data_engineering
      POSTGRES_DB: taxi_data

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: